services:
  secure-web-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - app-network

  git-server:
      build:
        dockerfile: gitserver.Dockerfile
        context: .
      restart: always
      ports:
        - "3001:3000"
      volumes:
        - ./repos:/home/git

networks:
  app-network:
    driver: bridge
